config/routes.rb
Universitycool::Application.routes.draw do
  
  get "pages/index"

  get "universities/index"

  namespace :admin do
    resources :universities
  end
  
  root :to => 'university_searches#new'
  
  resources :universities
  resources :university_searches
  resources :pages
  
  match "/about-us", :to => "university_searches#about_us", :as => :about_us
  
  match "/about-site", :to => "university_searches#about_site", :as => :about_site
  
end

app/models/university.rb
require 'httparty'

class University < ActiveRecord::Base
  include Geokit::Geocoders
  include HTTParty

  base_uri 'ajax.googleapis.com/'
  default_params :output => 'json'
  format :json
  
  validates :name, :uniqueness => true

  has_many :university_datas

  def months_relation
    output = []
    ["01", "02", "03", "04"].each do |month|
      output << self.students.to_f / UniversityData.last_year_on(self, month)
    end
    output
  end
  
  def logo
    query = "universidad de " + self.name + " logo"
    response = self.class.get('/ajax/services/search/images', :query => {:v => "1.0", :q => query})
    response.to_hash["responseData"]["results"].first["url"]
  end

  def self.populate
    Budget::University.get_universities.each do |uni|
      self.create :name => uni
    end
  end
  
  def map
    location = MultiGeocoder.geocode(self.address)
    "http://maps.google.com/maps/api/staticmap?center=#{address}Y&zoom=14&size=300x256&maptype=roadmap
    &markers=color:blue|label:S|#{location.ll}&sensor=false"
  end
  
  def salary_per_costs
    UniversityData.last_first_month(self)
  end
end

app/controllers/admin/universities_controller.rb
class Admin::UniversitiesController < Admin::AdminsController

  def index
    @universities = University.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @university }
    end
  end


  def show
    @university = University.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @university }
    end
  end

  
  def new
    @university = University.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @university }
    end
  end

  def edit
    @university = University.find(params[:id])
  end

 
  def create
    @university = University.new(params[:university])

    respond_to do |format|
      if @university.save
        format.html { redirect_to [:admin, @university], notice: 'University  was successfully created.' }
        format.json { render json: @university, status: :created, location: @university }
      else
        format.html { render action: "new" }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @university = University.find(params[:id])

    respond_to do |format|
      if @university.update_attributes(params[:university])
        format.html { redirect_to [:admin, @university], notice: 'University  was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @university.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @university = University.find(params[:id])
    @university.destroy

    respond_to do |format|
      format.html { redirect_to admin_universities_url }
      format.json { head :ok }
    end
  end
  
end

app/controllers/universities_controller.rb
class UniversitiesController < ApplicationController
end

app/helpers/universities_helper.rb
module UniversitiesHelper
end

app/views/admin/universities/_form.html.erb
  <%= form_for([:admin, @university]) do |f| %>
    <% if @university.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@university.errors.count, "error") %> prohibited this university from being saved:</h2>

        <ul>
        <% @university.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %> 
	  <p>
		<%=f.label :name%>
        <%= f.text_field :name, :placeholder => "Alias de la Universidad" %>
      </p>
	  <p>
		<%=f.label :alias%>
        <%= f.text_field :alias %>
      </p>
	  <p>
		<%=f.label :address%>
        <%= f.text_field :address %>
      </p>
	  <p>
		<%=f.label :rector%>
        <%= f.text_field :rector%>
      </p>
	  <p>
		<%=f.label :fundation%>
        <%= f.text_field :fundation%>
      </p>
	  <p>
		<%=f.label :students%>
        <%= f.text_field :students%>
      </p>
      <p>
        <%= f.submit "Guardar" %>
      </p>
  <% end %>

app/views/admin/universities/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', [:admin, @university] %> |
<%= link_to 'Back', admin_universities_path %>

app/views/admin/universities/index.html.erb
<h1>Listing universities</h1>

<table border="1">
  <tr>
    <th>University name</th>
    <th>Alias</th>
    <th>fundation</th>
    <th>address</th>
    <th>city</th>
	<th>rector</th>
	<th>students</th>
	<th></th>
	<th></th>
	<th></th>
  </tr>

<% @universities.each do |university| %>
  <tr>
    <td><%= university.name %></td>
    <td><%= university.alias %></td>
    <td><%= university.fundation %></td>
    <td><%= university.address %></td>
    <td><%= university.city %></td>
    <td><%= university.rector %></td>
    <td><%= university.students %></td>
    <td><%= link_to 'Show', [:admin, university] %></td>
    <td><%= link_to 'Edit', edit_admin_university_path(university) %></td>
    <td><%= link_to 'Destroy', [:admin, university], confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New University', new_admin_university_path %>

app/views/admin/universities/new.html.erb
	<%= render 'form' %>

	<%= link_to 'Back', admin_universities_path %>

app/views/admin/universities/show.html.erb
<div>Name: <%=@university.name%></div>
<div>Alias: <%=@university.name%></div>
<div><%= link_to 'Back', admin_universities_path %></div>