config/routes.rb
Universitycool::Application.routes.draw do
  
  get "pages/index"

  get "universities/index"

  namespace :admin do
    resources :universities
  end
  
  root :to => 'university_searches#new'
  
  resources :universities
  resources :university_searches
  resources :pages
  
  match "/about-us", :to => "university_searches#about_us", :as => :about_us
  
  match "/about-site", :to => "university_searches#about_site", :as => :about_site
  
end

app/models/university_search.rb
class UniversitySearch < ActiveRecord::Base
  validates :university_name, :presence => true
end

app/controllers/university_searches_controller.rb
class UniversitySearchesController < ApplicationController

  def index
    @university_searches = UniversitySearch.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @university_searches }
    end
  end

  def show
    @university_search = UniversitySearch.find(params[:id])
    @university = University.find_by_alias(@university_search.university_name)
    @universities = University.all
    #@result = BudgetUniversity.new(object)
    @university_search = UniversitySearch.new
    if @university
      @months, @money = UniversityData.presupuestos(@university)
      @salaries = UniversityData.salaries(@university)
    end
    if @university && @university.alias == "UBA"
      @students_enrollment = StudentsEnrollment.where(:university => "Universidad de Buenos Aires").order("last_enrollment desc").limit(5)
    end
    respond_to do |format|
      unless @university.nil?
        format.html # show.html.erb
        format.json { render json: @university_search }
      else
        @university_search.errors.add :base, "No se ha encontrado esa universidad."
        format.html { render action: "new" }
      end
    end
  end

  
  def new
    @university_search = UniversitySearch.new
    @universities = University.all
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @university_search }
    end
  end

  def edit
    @university_search = UniversitySearch.find(params[:id])
  end

 
  def create
    @university_search = UniversitySearch.new(params[:university_search])

    respond_to do |format|
      if @university_search.save
        format.html { redirect_to @university_search, notice: 'University search was successfully created.' }
        format.json { render json: @university_search, status: :created, location: @university_search }
      else
        @universities = University.all
        format.html { render action: "new" }
        format.json { render json: @university_search.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    @university_search = UniversitySearch.find(params[:id])

    respond_to do |format|
      if @university_search.update_attributes(params[:university_search])
        format.html { redirect_to @university_search, notice: 'University search was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @university_search.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @university_search = UniversitySearch.find(params[:id])
    @university_search.destroy

    respond_to do |format|
      format.html { redirect_to university_searches_url }
      format.json { head :ok }
    end
  end

  def about_us

  end

  def about_site
    
  end
end

app/helpers/university_searches_helper.rb
module UniversitySearchesHelper
end

app/views/university_searches/_form.html.erb
  <%= form_for(@university_search) do |f| %>
    <div class="all-form">

    <% if @university_search.errors.any? %>
      <div>
        <% @university_search.errors.full_messages.each do |msg| %>
          <div><%= msg %></div>
        <% end %>
      </div>
    <% end %>
      <div class="new-form-fields">
        <%= f.text_field :university_name, :placeholder => "Acronimo de la Universidad", :id => "ui-autocomplete-input" %>
      </div>


       <script>
        $(function() {
        

          var availableTags = [];

          <% @universities.each do |u| %>
             availableTags.push("<%=u.alias%>");
          <% end %>
          $( "#ui-autocomplete-input" ).autocomplete({
            source: availableTags
          });
        });
      </script>


      <div class="new-form-submit-image">
        <%= f.submit "Buscar",:id=>"search-university-btn", :class=>"university-btn" %>
      </div>
  </div>
  <% end %>

app/views/university_searches/about_us.html.erb
<div class="header">
  <div class="title">Datos Universitarios</div>
</div>

<div class="about-us-title">Team</div>
<div class="our-info">

	<div class="our-info-left">
		  <div class="user-info">
		  	<div class="user-info-image"><%= image_tag("marcos_image.jpg") %></div>
		  	  <div class="user-info-text">
			  	<div class="user-info-name">Marcos Vanetta</div>
			  	<div class="user-info-description">Ingeniero Biomédico</div>
			  </div>
		  </div>
		  <div class="clear"></div>
	</div>


	  <div class="our-info-right">
		  <div class="user-info-right">
		  	<div class="user-info-image-right"><%= image_tag("alejandro_image.png") %></div>
		  	  <div class="user-info-text">
			  	<div class="user-info-name">Alejandro Alvarez</div>
			  	<div class="user-info-description-right">Estudiante de Ingeniería en Informática</div>
			  </div>
		  </div>
		  <div class="clear"></div>
	  </div>


	  
	<div class="our-info-down">
		  <div class="user-info-down">
		  	
		  	  <div class="user-info-text-down">
			  	<div class="user-info-name">Lucas Minissale</div>
			  	<div class="user-info-description">Licenciado en Informática</div>
			  </div>
			<div class="user-info-image-down"><%= image_tag("lucas_image.jpg") %></div>  
		  </div>
		  <div class="clear"></div>
	</div>
	  

</div>
<div class="footer">
  <div class="footer-image"><%#= image_tag("ruby_image.png") %></div>
</div>

app/views/university_searches/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @university_search %> |
<%= link_to 'Back', university_searches_path %>

app/views/university_searches/index.html.erb
<h1>Listing university_searches</h1>

<table>
  <tr>
    <th>University name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @university_searches.each do |university_search| %>
  <tr>
    <td><%= university_search.university_name %></td>
    <td><%= link_to 'Show', university_search %></td>
    <td><%= link_to 'Edit', edit_university_search_path(university_search) %></td>
    <td><%= link_to 'Destroy', university_search, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New University search', new_university_search_path %>

app/views/university_searches/new.html.erb
<div class="header">
 	<div class="title">Datos Universitarios</div>
</div>
<div class="home">
	<div class="new-form">
		<%= render 'form' %>
		<div class="new-about">
		  <%=link_to "Acerca de nosotros", about_us_path%>
		  <%=link_to "Más datos", '/pages' %>
		</div>
	</div>
</div>

<div class="footer">
  <div class="footer-image"><%= image_tag("ruby_image.png") %></div>
</div>

app/views/university_searches/show.html.erb
<div class="wrapped">
	<div class="show-form">
		<%= render 'form' %>
	</div>
	<div class="container">
		<div class="top">
			<div class="map">
				<%= image_tag @university.map %>
				<div class="clear"></div>
			</div>
			<div class="map">
				<%= image_tag @university.logo, :width=>"250"%>
			</div>
			<div class="main-info">
				<div class="university-name">
					<span>
						<%= @university.alias %>
					</span>
				</div>
				<div class="university-address">
					<span>
						<%= @university.address%>
					</span>
				</div>
				<div>
					<span>
						Rector de la universidad - <%= @university.rector%>
					</span>
				</div>
				<div>
					<span>
						Cantidad de estudiantes - <%= @university.students%>
					</span>
				</div>
			</div>	
			<div class="clear"></div>
		</div>
		<div class="bottom">
			<%= render :partial=> "/shared/graphic", :locals => { :money => @money, :months => @months, :title => 'Presupuesto mensual', :id => 'presupuestos'}%>
			<%= render :partial=> "/shared/graphic", :locals => { :money => @salaries, :months => @months, :title => 'Salarios acumulados', :id => 'salarios'}%>
			<div class='desertion_relation' id='desertion_relation'></div>
<script>
var chart;
<% if @students_enrollment %>
$(document).ready(function() {
   chart = new Highcharts.Chart({
      chart: {
         renderTo: 'desertion_relation',
         plotBackgroundColor: null,
         plotBorderWidth: null,
         plotShadow: false
      },
      title: {
         text: 'Tasa de deserción por carrera.'
      },
      tooltip: {
         formatter: function() {
            return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
         }
      },
      plotOptions: {
         pie: {
            allowPointSelect: true,
            cursor: 'pointer',
            dataLabels: {
               enabled: true,
               color: Highcharts.theme.textColor || '#000000',
               connectorColor: Highcharts.theme.textColor || '#000000',
               formatter: function() {
                  return '<b>'+ this.point.name +'</b>: '+ this.percentage +' %';
               }
            }
         }
      },
       series: [{
         type: 'pie',
         name: 'Tasa de deserción',
         data: [
             <% @students_enrollment.each do |st| %>
               ["<%= st.career %>", <%= st.desertion_relation %>],
             <% end %>
         ]
      }]
   });
});
</script>
<% end %>
		</div>
	</div>
	<div class="clear"></div>
</div>